# Generated by Django 5.2.5 on 2026-05-03 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflow', '0002_add_multiformat_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannertemplate',
            name='background_image',
        ),
        migrations.AddField(
            model_name='bannertemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bannertemplate',
            name='canvas_data',
            field=models.JSONField(default=dict, help_text='Fabric.js canvas JSON data'),
        ),
    ]
