# Generated by Django 5.2 on 2026-05-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appflow', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('store_name', models.CharField(blank=True, default='', max_length=120)),
                ('offer_price', models.CharField(blank=True, default='', max_length=80)),
                ('source_url', models.URLField(blank=True, default='')),
                ('ratio', models.CharField(default='1:1', max_length=20)),
                ('image', models.ImageField(upload_to='generated_banners/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_banners', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_banners', to='appflow.bannertemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
